--CREATE DATABASE MovieTheaters;
--CREATE SCHEMA Theaters;

DROP TABLE IF EXISTS Theaters.Theater
DROP TABLE IF EXISTS Theaters.Staff
DROP TABLE IF EXISTS Theaters.Showing
DROP TABLE IF EXISTS Theaters.Movies
DROP TABLE IF EXISTS Theaters.Tickets

CREATE TABLE Theaters.Theater
(
	TheaterId INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Location NVARCHAR(64) NOT NULL,
	Name NVARCHAR(64) NOT NULL,

	UNIQUE(Location, Name)
);

CREATE TABLE Theaters.Staff
(
	StaffId INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	TheaterId INT FOREIGN KEY REFERENCES Theaters.Theater(TheaterId),
	Hours INT NOT NULL,
	HourlyPay INT NOT NULL,

	--UNIQUE(Hours, HourlyPay)
);

CREATE TABLE Theaters.Movies
(
	MovieId INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	MovieName NVARCHAR(128) NOT NULL,
	Genre NVARCHAR(64) NOT NULL,
	ReviewRating INT NOT NULL,
	ReleaseDate INT NOT NULL,

	--UNIQUE(Genre, ReleaseDate, MovieName, ReviewRating)
);

CREATE TABLE Theaters.Showing
(
	RoomId INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	TheaterId INT NOT NULL FOREIGN KEY REFERENCES Theaters.Theater(TheaterId),
	MovieId INT NOT NULL FOREIGN KEY REFERENCES Theaters.Movies(MovieId),
	ShowTime DATETIMEOFFSET NOT NULL DEFAULT(GETDATE()),
	ShowDate DATETIMEOFFSET NOT NULL DEFAULT(GETDATE()),

	--UNIQUE(ShowTime, ShowDate)
);

CREATE TABLE Theaters.Tickets
(
	MovieId INT NOT NULL PRIMARY KEY FOREIGN KEY REFERENCES Theaters.Movies(MovieID),
	TicketPrice INT NOT NULL,
	TicketSold INT NOT NULL,

	--UNIQUE(TicketPrice, TicketSold)
);

INSERT INTO Theaters.Theater VALUES
    (N'Lewiston',N'Society Theater'),
    (N'Pocatello',N'Depth Theater'),
    (N'Pike Creek',N'Engineering Theater'),
    (N'Flint',N'Population Theater'),
    (N'Detroit',N'Category Theater'),
    (N'Baton Rouge',N'Nation Theater'),
    (N'Wichita',N'Pie Theater'),
    (N'Kailua',N'Heart Theater'),
    (N'Los Angeles',N'Television Theater'),
    (N'Augusta',N'Anxiety Theater'),
    (N'Akron',N'Refrigerator Theater'),
    (N'Rutland',N'Difference Theater'),
    (N'Richmond',N'Tale Theater'),
    (N'Rutland',N'Boyfriend Theater'),
    (N'Dover',N'Reality Theater'),
    (N'Hattiesburg',N'Assumption Theater'),
    (N'North Las Vegas',N'Temperature Theater'),
    (N'Billings',N'Situation Theater'),
    (N'Birmingham',N'Perspective Theater'),
    (N'Miami',N'Son Theater'),
    (N'Newark',N'Description Theater'),
    (N'Bridgeport',N'Hair Theater'),
    (N'Portland',N'Blood Theater'),
    (N'Biloxi',N'Skill Theater'),
    (N'Dover',N'Power Theater'),
    (N'San Diego',N'Teaching Theater'),
    (N'Chesapeake',N'Protection Theater'),
    (N'Hilo',N'Operation Theater'),
    (N'Springfield',N'Engine Theater'),
    (N'Waterbury',N'Medicine Theater'),
    (N'Jonesboro',N'Effort Theater'),
    (N'Indianapolis',N'Method Theater'),
    (N'Kaneohe',N'Application Theater'),
    (N'Cedar Rapids',N'Inflation Theater'),
    (N'Annapolis',N'Poem Theater'),
    (N'Missoula',N'Failure Theater'),
    (N'Dover',N'Administration Theater'),
    (N'St. Petersburg',N'Studio Theater'),
    (N'Virginia Beach',N'Advertising Theater'),
    (N'Athens',N'Policy Theater'),
    (N'Worcester',N'Basis Theater'),
    (N'Oklahoma City',N'Resource Theater'),
    (N'Jacksonville',N'Selection Theater'),
    (N'Bellevue',N'Driver Theater'),
    (N'Lowell',N'Cookie Theater'),
    (N'Newark',N'Analyst Theater'),
    (N'Grand Island',N'World Theater'),
    (N'Gulfport',N'Sympathy Theater'),
    (N'Minneapolis',N'Obligation Theater'),
    (N'San Diego',N'Impression Theater'),
    (N'Montpelier',N'Battery Theater'),
    (N'Columbia',N'Glove Theater'),
    (N'Idaho Falls',N'Hit Theater'),
    (N'Green Bay',N'Carpet Theater'),
    (N'Houston',N'Matter Theater'),
    (N'Bellevue',N'Horseshoe Theater'),
    (N'Duluth',N'Budget Theater'),
    (N'Lincoln',N'Nose Theater'),
    (N'Iowa City',N'Rabbit Theater'),
    (N'Duluth',N'Adopt Theater'),
    (N'Metairie',N'Affinity Theater'),
    (N'Essex',N'Band Theater'),
    (N'Worcester',N'Additional Theater'),
    (N'Kansas City',N'Nest Theater'),
    (N'Cincinnati',N'Collect Theater'),
    (N'Juneau',N'Volume Theater'),
    (N'Auburn',N'Contain Theater'),
    (N'Laramie',N'Mastermind Theater'),
    (N'Cleveland',N'Directory Theater'),
    (N'Rockville',N'Apathy Theater'),
    (N'New Haven',N'Fit Theater'),
    (N'Carson City',N'Invite Theater'),
    (N'Toledo',N'Policeman Theater'),
    (N'Hilo',N'Functional Theater'),
    (N'Wyoming',N'Stab Theater'),
    (N'Nampa',N'Charge Theater'),
    (N'Fort Collins',N'Oh Theater'),
    (N'Casper',N'Carbon Theater'),
    (N'Huntsville',N'Line Theater'),
    (N'Paradise',N'Vat Theater'),
    (N'Fayetteville',N'Heir Theater'),
    (N'Frankfort',N'Cottage Theater'),
    (N'Cheyenne',N'Hesitate Theater'),
    (N'Duluth',N'Court Theater'),
    (N'Georgia',N'Convert Theater'),
    (N'Rutland',N'Steel Theater'),
    (N'Joliet',N'Mess Theater'),
    (N'Kapolei',N'Portrait Theater'),
    (N'Missoula',N'Harvest Theater'),
    (N'Georgia',N'Choose Theater'),
    (N'Tampa',N'Diplomat Theater'),
    (N'Helena',N'Allowance Theater'),
    (N'Colorado Springs',N'History Theater'),
    (N'Gillette',N'Charm Theater'),
    (N'Gary',N'Critic Theater'),
    (N'Kansas City',N'Management Theater'),
    (N'Grand Rapids',N'Sphere Theater'),
    (N'Idaho Falls',N'Broadcast Theater'),
    (N'Lewiston',N'Demonstrate Theater'),
    (N'Aurora;',N'Of Theater');

INSERT INTO Theaters.Movies VALUES
    ('Youth in Revolt','Comedy',52,2010),
    ('You Will Meet a Tall Dark Stranger','Comedy',35,2010),
    ('When in Rome','Comedy',44,2010),
    ('What Happens in Vegas','Comedy',72,2008),
    ('Water For Elephants','Drama',72,2011),
    ('WALL-E','Animation',89,2008),
    ('Waitress','Romance',67,2007),
    ('Waiting For Forever','Romance',53,2011),
    ('Valentine''s Day','Comedy',54,2010),
    ('Tyler Perry''s Why Did I get Married','Romance',47,2007),
    ('Twilight: Breaking Dawn','Romance',68,2011),
    ('Twilight','Romance',82,2008),
    ('The Ugly Truth','Comedy',68,2009),
    ('The Twilight Saga: New Moon','Drama',78,2009),
    ('The Time Traveler''s Wife','Drama',65,2009),
    ('The Proposal','Comedy',74,2009),
    ('The Invention of Lying','Comedy',47,2009),
    ('The Heartbreak Kid','Comedy',41,2007),
    ('The Duchess','Drama',68,2008),
    ('The Curious Case of Benjamin Button','Fantasy',81,2008),
    ('The Back-up Plan','Comedy',47,2010),
    ('Tangled','Animation',88,2010),
    ('Something Borrowed','Romance',48,2011),
    ('She''s Out of My League','Comedy',60,2010),
    ('Sex and the City 2','Comedy',49,2010),
    ('Sex and the City','Comedy',81,2008),
    ('Remember Me','Drama',70,2010),
    ('Rachel Getting Married','Drama',61,2008),
    ('Penelope','Comedy',74,2008),
    ('P.S. I Love You','Romance',82,2007),
    ('Over Her Dead Body','Comedy',47,2008),
    ('Our Family Wedding','Comedy',49,2010),
    ('One Day','Romance',54,2011),
    ('Not Easily Broken','Drama',66,2009),
    ('No Reservations','Comedy',64,2007),
    ('Nick and Norah''s Infinite Playlist','Comedy',67,2008),
    ('New Year''s Eve','Romance',48,2011),
    ('My Week with Marilyn','Drama',84,2011),
    ('Music and Lyrics','Romance',70,2007),
    ('Monte Carlo','Romance',50,2011),
    ('Miss Pettigrew Lives for a Day','Comedy',70,2008),
    ('Midnight in Paris','Romence',84,2011),
    ('Marley and Me','Comedy',77,2008),
    ('Mamma Mia!','Comedy',76,2008),
    ('Made of Honor','Comdy',61,2008),
    ('Love Happens','Drama',40,2009),
    ('Love & Other Drugs','Comedy',55,2010),
    ('Life as We Know It','Comedy',62,2010),
    ('License to Wed','Comedy',55,2007),
    ('Letters to Juliet','Comedy',62,2010),
    ('Leap Year','Comedy',49,2010),
    ('Knocked Up','Comedy',83,2007),
    ('Killers','Action',45,2010),
    ('Just Wright','Comedy',58,2010),
    ('Jane Eyre','Romance',77,2011),
    ('It''s Complicated','Comedy',63,2009),
    ('I Love You Phillip Morris','Comedy',57,2010),
    ('High School Musical 3: Senior Year','Comedy',76,2008),
    ('He''s Just Not That Into You','Comedy',60,2009),
    ('Good Luck Chuck','Comedy',61,2007),
    ('Going the Distance','Comedy',56,2010),
    ('Gnomeo and Juliet','Animation',52,2011),
    ('Ghosts of Girlfriends Past','Comedy',47,2009),
    ('Four Christmases','Comedy',52,2008),
    ('Fireproof','Drama',51,2008),
    ('Enchanted','Comedy',80,2007),
    ('Dear John','Drama',66,2010),
    ('Beginners','Comedy',80,2011),
    ('Across the Universe','Romance',84,2007),
    ('A Serious Man','Drama',64,2009),
    ('A Dangerous Method','Drama',89,2011),
    ('27 Dresses','Comedy',71,2008),
    ('(500) Days of Summer','Comedy',81,2009);

/*INSERT INTO Theaters.Staff(Hours, HourlyPay) VALUES
    (34.0,11.0),
    (14.0,8.0),
    (14.0,12.0),
    (9.0,8.0),
    (18.0,9.0),
    (18.0,9.0),
    (25.0,7.0),
    (40.0,9.0),
    (39.0,8.0),
    (32.0,12.0),
    (28.0,9.0),
    (20.0,10.0),
    (24.0,12.0),
    (17.0,8.0),
    (5.0,12.0),
    (6.0,9.0),
    (17.0,12.0),
    (1.0,12.0),
    (38.0,9.0),
    (26.0,12.0),
    (14.0,10.0),
    (7.0,12.0),
    (7.0,11.0),
    (15.0,7.0),
    (22.0,8.0),
    (38.0,8.0),
    (8.0,7.0),
    (16.0,11.0),
    (18.0,8.0),
    (26.0,7.0),
    (26.0,7.0),
    (7.0,7.0),
    (4.0,7.0),
    (36.0,11.0),
    (32.0,12.0),
    (21.0,11.0),
    (28.0,11.0),
    (32.0,7.0),
    (38.0,8.0),
    (28.0,7.0),
    (35.0,7.0),
    (19.0,11.0),
    (25.0,11.0),
    (11.0,9.0),
    (19.0,12.0),
    (13.0,10.0),
    (36.0,7.0),
    (22.0,7.0),
    (32.0,11.0),
    (26.0,12.0),
    (29.0,7.0),
    (40.0,7.0),
    (17.0,8.0),
    (1.0,12.0),
    (27.0,7.0),
    (35.0,9.0),
    (32.0,10.0),
    (22.0,9.0),
    (13.0,11.0),
    (21.0,11.0),
    (13.0,9.0),
    (34.0,11.0),
    (13.0,9.0),
    (32.0,10.0),
    (35.0,9.0),
    (13.0,8.0),
    (8.0,8.0),
    (6.0,7.0),
    (9.0,7.0),
    (39.0,11.0),
    (11.0,12.0),
    (35.0,11.0),
    (3.0,8.0),
    (23.0,8.0),
    (20.0,10.0),
    (10.0,9.0),
    (21.0,11.0),
    (23.0,11.0),
    (25.0,10.0),
    (25.0,8.0),
    (27.0,7.0),
    (11.0,7.0),
    (24.0,8.0),
    (39.0,11.0),
    (15.0,8.0),
    (17.0,12.0),
    (22.0,8.0),
    (10.0,11.0),
    (36.0,12.0),
    (26.0,8.0),
    (19.0,8.0),
    (12.0,8.0),
    (14.0,9.0),
    (2.0,10.0),
    (33.0,9.0),
    (30.0,9.0),
    (6.0,11.0),
    (11.0,10.0),
    (35.0,10.0),
    (27.0,7.0);*/



